using System;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

namespace OLEWriter
{
    [SupportedOSPlatform("windows")]
    class Program
    {
        [DllImport("ole32.dll", CharSet = CharSet.Unicode, PreserveSig = true)]
        static extern int StgCreateStorageEx(
            string pwcsName, uint grfMode, uint stgfmt, uint grfAttrs,
            IntPtr pStgOptions, IntPtr reserved2,
            ref Guid riid, out IStorage ppObjectOpen);

        static void Main(string[] args)
        {
            string serialNumber = args.Length > 0 ? args[0] : "85640531";
            string filePath = "SampleData.vi2";
            Guid iidStorage = OleConstants.IID_IStorage;

            int hr = StgCreateStorageEx(filePath, OleConstants.STGM_RW_EXCL_CREATE, 0, 0,
                IntPtr.Zero, IntPtr.Zero, ref iidStorage, out IStorage rootStorage);

            if (hr != 0) { Console.WriteLine($"StgCreateStorageEx failed: 0x{hr:X8}"); return; }

            try
            {
                rootStorage.CreateStorage("30438", OleConstants.STGM_RW_EXCL_CREATE, 0, 0, out IStorage ss_30438);
                rootStorage.CreateStream("org", OleConstants.STGM_RW_EXCL_CREATE, 0, 0, out var orgStream);

                ss_30438.CreateStorage("data", OleConstants.STGM_RW_EXCL_CREATE, 0, 0, out IStorage data);
                ss_30438.CreateStorage("channels", OleConstants.STGM_RW_EXCL_CREATE, 0, 0, out IStorage channels);

                rootStorage.Commit(0);

                Marshal.ReleaseComObject(channels);
                Marshal.ReleaseComObject(data);
                Marshal.ReleaseComObject(ss_30438);
                Marshal.ReleaseComObject(orgStream);

                Console.WriteLine("Success! File created with Summary Information.");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
                Console.WriteLine($"Stack trace: {ex.StackTrace}");
            }
            finally
            {
                if (Marshal.IsComObject(rootStorage)) Marshal.ReleaseComObject(rootStorage);
            }
        }

        static void WriteSummaryInformation(IStorage rootStorage, string serialNumber)
        {
            IPropertySetStorage propSetStorage = (IPropertySetStorage)rootStorage;
            Guid fmtid = OleConstants.Fmtid_SummaryInformation;
            Guid clsid = Guid.Empty;

            int createHr = propSetStorage.Create(ref fmtid, ref clsid, 0, OleConstants.STGM_RW_EXCL_CREATE, out IPropertyStorage propStorage);
            if (createHr != 0) throw new COMException($"IPropertySetStorage.Create failed: 0x{createHr:X8}", createHr);

            try
            {
                // PIDSI_TITLE=2, PIDSI_AUTHOR=4, PIDSI_COMMENTS=6
                PROPSPEC[] specs = new PROPSPEC[3];
                specs[0] = new PROPSPEC { ulKind = OleConstants.PRSPEC_PROPID, propid = 2 };
                specs[1] = new PROPSPEC { ulKind = OleConstants.PRSPEC_PROPID, propid = 4 };
                specs[2] = new PROPSPEC { ulKind = OleConstants.PRSPEC_PROPID, propid = 6 };

                PROPVARIANT[] vars = new PROPVARIANT[3];
                vars[0] = MakeLpwstr("Sample VI2 File");
                vars[1] = MakeLpwstr($"t17b:{serialNumber}");
                vars[2] = MakeLpwstr("Generated by OLEWriter");

                int writeHr = propStorage.WriteMultiple(3, specs, vars, 2);

                foreach (var v in vars)
                    if (v.ptr != IntPtr.Zero) Marshal.FreeCoTaskMem(v.ptr);

                if (writeHr != 0) throw new COMException($"WriteMultiple failed: 0x{writeHr:X8}", writeHr);
            }
            finally
            {
                Marshal.ReleaseComObject(propStorage);
            }
        }

        static PROPVARIANT MakeLpwstr(string s) => new PROPVARIANT
        {
            vt  = OleConstants.VT_LPWSTR,
            ptr = Marshal.StringToCoTaskMemUni(s ?? string.Empty)
        };
    }
}
